# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app5_aggarwal_arushi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app5_aggarwal_arushi

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
pod 'Firebase/Firestore'
# https://firebase.google.com/docs/ios/setup#available-pods

  target 'app5_aggarwal_arushiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'app5_aggarwal_arushiUITests' do
    # Pods for testing
  end

end
